/* Meaningful checks for the rule model, malformed serial traffic, alignment
   invariance, supplied-coordinate identity and original-file preservation. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const E=require('../js/engine.js');let checks=0;function check(fn){fn();checks++;}
check(()=>assert.deepEqual(E.chemistry('P').scores,[65,25,70]));check(()=>assert.deepEqual(E.chemistry('A').scores,[35,25,55]));check(()=>assert.deepEqual(E.chemistry('G').scores,[35,25,55]));check(()=>assert.deepEqual(E.chemistry('S').scores,[0,0,0]));
check(()=>assert.throws(()=>E.chemistry('Z')));check(()=>assert.equal(E.teaching('P','Mutant',100,true,'Network').value,100));check(()=>assert.equal(E.teaching('P','WT',100,true,'Network').value,50));check(()=>assert.equal(E.teaching('P','Mutant',3,false,'DNA').stress,0));
for(const [value,mode] of [[0,'Structure'],[341,'Structure'],[342,'DNA'],[682,'DNA'],[683,'Network'],[1023,'Network'],[-4,'Structure'],[3000,'Network']])check(()=>assert.equal(E.modeFromPot(value),mode));
for(const [pressure,contact,band] of [[0,false,'YELLOW'],[20,false,'RED'],[0,true,'RED']])check(()=>assert.equal(E.teaching('P','Mutant',pressure,contact,'Structure').band,band));
const d=new E.SerialDecoder();check(()=>assert.deepEqual(d.feed('POT:70'),[]));check(()=>assert.equal(d.feed('0 MIC:512\n')[0].pot,700));check(()=>assert.equal(d.parse('DBG:P0=100 P2=1023',100).pressure,100));check(()=>assert.equal(d.parse('POT:99999 MIC:-1 CONTACT:1').pot,1023));check(()=>assert.equal(d.parse('P1:1'),null));check(()=>assert.equal(d.parse('CONTACT:0').contact,false));
check(()=>assert.equal(d.parse('EVT:A SEQ:10',1).event,'A'));check(()=>assert.equal(d.parse('EVT:A SEQ:10',900).event,null));check(()=>assert.equal(d.parse('EVT:B SEQ:11',1000).event,'B'));
check(()=>assert.equal(d.parse('A',0).event,'A'));for(let t=250;t<=2000;t+=250)check(()=>assert.equal(d.parse('A',t).event,null));check(()=>assert.equal(d.parse('A',2600).event,'A'));check(()=>assert.equal(d.parse('<script>alert(1)</script>'),null));check(()=>assert.equal(d.parse('X'.repeat(1500)),null));check(()=>assert.deepEqual(d.feed('X'.repeat(9000)),[]));
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../data/models.js'),'utf8'),ctx);const D=ctx.window.MUTA_DATA;check(()=>assert.equal(Object.keys(D.models).length,7));check(()=>assert.equal(D.audit.changes.length,1));check(()=>assert.equal(D.audit.changes[0].resi,231));check(()=>assert.equal(D.audit.changes[0].wt,'SER'));check(()=>assert.equal(D.audit.changes[0].mutant,'PRO'));
check(()=>assert.equal(D.models.foxa2_wt.atoms.find(a=>a.name==='CA'&&a.resi===169).resn,'THR'));check(()=>assert.ok(Math.abs(D.audit.metrics.local.rmsd-.364130473896)<1e-9));check(()=>assert.ok(D.audit.metrics.local.rmsd<D.audit.metrics.local.rawRmsd));
check(()=>assert.equal(D.audit.dnaContactsUnder4A.length,6));check(()=>assert.ok(Math.abs(D.audit.dnaContactsUnder4A[0].distance-2.421287673945)<1e-9));check(()=>assert.ok(D.models.foxa2_dna.atoms.some(a=>a.chain==='F'&&a.resi===231&&a.name==='CA'&&a.labelResi==='77')));
const refs=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/reference-accessions.json')));check(()=>assert.equal(D.models.foxa2_wt.sequence,refs.find(r=>r.accession==='Q9Y261').sequence));
const inventory=JSON.parse(fs.readFileSync(path.join(__dirname,'../source-inventory.json')));check(()=>assert.equal(inventory.files.length,19));for(const f of inventory.files)check(()=>assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',f.packagePath))).digest('hex'),f.sha256));
console.log(`${checks} checks passed: scoring, input bounds, fragmented serial messages, duplicate events, coordinate audit and original-file hashes.`);
